// <auto-generated />
namespace Village_Test.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Add_residents_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_residents_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202201190902236_Add_residents_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
